name: SparkMMO
main: org.jbltd.mmo.core.Main
version: 0.1-ALPHA
author: SparkWings

commands:
    chat:
    broadcast:
    message:
        aliases: [message, msg, m, whisper, w, tell]
    reply:
        aliases: [reply, r]
    guild:
        aliases: [guild, g, faction, factions, guilds, f, clan, c]
    escape:
    invite:
    accept:
    deny: